INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Sengelinned', 30, 0);
INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Morgenkomplet for voksen', 75, 0);
INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Morgenkomplet for barn', 50, 0);
INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Cykelleje', 200, 1);
INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Adgang til badeland for voksen', 30, 0);
INSERT INTO Additions(Name, Price, IsDailyPayment) VALUES('Adgang til badeland for barn', 15, 0);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('221', 1, 0);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('220', 1, 0);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('219', 1, 0);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('218', 1, 0);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('217', 1, 0);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('216', 1, 0);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('80', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('79', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('78', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('77', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('76', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('75', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('73', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('72', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('70', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('68', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('67', 1, 1);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('199', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('198', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('197', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('190', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('196', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('195', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('193', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('192', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('191', 1, 1);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('2', 2, 0);
INSERT INTO CampingSpots(Number, CampingType) VALUES('2', 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('3', 2, 0);
INSERT INTO CampingSpots(Number, CampingType) VALUES('3', 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('4', 2, 0);
INSERT INTO CampingSpots(Number, CampingType) VALUES('4', 2);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('130', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('130', 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('133', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('133', 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('129', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('129', 1);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('183', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('183', 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('184', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('184', 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('181', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('181', 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('182', 2, 1);
INSERT INTO CampingSpots(Number, CampingType) VALUES('182', 2);

INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H2', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H2', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H3', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H3', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H4', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H4', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H5', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H5', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H7', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H7', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H8', 3, 1);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H8', 1, 1);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H10', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H10', 1, 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H11', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H11', 1, 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H12', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H12', 1, 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H13', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H13', 1, 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H14', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H14', 1, 2);
INSERT INTO Spots(Number, SpotType, IsGoodView) VALUES('H15', 3, 0);
INSERT INTO HutSpots(Number, IsCleaned, HutType) VALUES('H15', 1, 2);